sqlsaturday/sqlsatwebsite

_data/events/SQLSat1021.yml, _posts/2021-10-31-sqlsaturday1021.markdown
=> Orlando2021

_data/events/SQLSat1021.yml
=> map url update

_data/events/SQLSat1022.yml
=> adding location information

_data/events/SQLSat1022.yml, _data/events/SQLSat1023.yml
=> please update asap

_data/events/SQLSat1026.yml
Resize the logos by sponsor type. (Hopefully for the last time)
Also, mark the CfS as closed.
=> Baton Rouge: Resize logos and close CfS

_data/events/SQLSat1045.yml, _posts/2023-03-18-sqlsaturday1045.markdown
Cleaning up markdown file, and correcting and fleshing out the YAML
- Changed `primarytag` in YAML
- Changed `data` in markdown file
=> Baton Rouge BI Edition #1045

_data/events/SQLSat1043.yml
SQLSatAustin - Updated the Schedule and Speakers.
=> Austin - Updated Schedule and Speakers

_data/events/SQLSat1043.yml
=> Austin - Sponsor Update fix

_data/events/SQLSat1043.yml
Gave Sios correct sponsorship title; added Solarwinds as sponsors.
=> Austin - Sponsor updates

_data/events/SQLSat1043.yml
=> Austin - Update Sponsor Image

_data/events/SQLSat1045.yml
Changed Sessionize URL and changed image sizes
=> SQLSatBR - session url changed and image sizes

_data/events/SQLSat1045.yml
=> SQLSATBR - removing idera

_data/events/SQLSat1045.yml
Changing sponsor level of texchix from silver to gold
=> SQLSATBR - Sponsor level

_data/events/SQLSat1055.yml
added more info, reposted schedule url, ok, more stuff added.
=> sqlsat1055 yml update2

_data/events/SQLSat1055.yml
=> update sqlsat1055 yml - add schedule

_data/events/SQLSat1055.yml
trying to fix schedule showing
=> sqlsat1055 yml

_data/events/SQLSat1055.yml
=> sqlsat1055 schedule fix attempt 987

_data/events/SQLSat1058.yml
=> columbus fixes

_data/events/SQLSat1060.yml
Adding Redgate as Bronze Sponsor
#1060
=> 1060 - Adding Redgate as bronze sponsor

_data/events/SQLSat1053.yml
Correcting the link to use sessionize directly. My apologize for submitting a correction
=> Correcting the Session URL from sessionize

_data/events/SQLSat1054.yml
=> Updated SQL Saturday Minnesota website, added details

_data/events/SQLSat1053.yml
We need to change the location to across the street. 
Last minute change. sorry!
=> Urgent location changed

_data/events/SQLSat1060.yml
=> Baton Rouge: Add Solarwinds

_data/events/SQLSat1060.yml
URL was incorrect due to c/p error
=> Baton Rouge: Correct Rubrik Link

_data/events/SQLSat1060.yml, batonrouge.html
=> Baton Rouge: Add Kuvare

_data/events/SQLSat1054.yml
Just for fun we added the speaker list because needed
=> Sessionize speaker list added

_data/events/SQLSat1054.yml
Update. Logos added and coming schedule
=> General update in lieu of event

_data/events/SQLSat1061.yml
=> Update SQLSat1061.yml with correct location of logo file

_data/events/SQLSat1054.yml
=> MNSQLSat precon details updated

_data/events/SQLSat1064.yml
=> Toronto meetup add

_includes/nav.html, _includes/pass-banner.html, assets/css/beautifuljekyll.css, assets/css/pass-banner.css
Fully built and tested locally.
=> Add pass 2023 banner

_includes/pass-banner.html
Switching banner to livestream messaging in the run up to event.
=> Add livestream messaging

_data/events/SQLSat1071.yml
Updated registration link & precons
=> Updated registration links & precons

_data/events/SQLSat1071.yml
Added ProcureSQL sponsorship to the website.
=> Updated ProcureSQL sponsorship.

_data/events/SQLSat1071.yml
Used an incorrect file extension for the logo.  Changed from png to jpg
=> Issue with logo file extension changed from to jpg

_data/events/SQLSat1075.yml, _posts/2024-01-27-sqlsaturday1075.markdown
=> guatemala testevent

_data/events/SQLSat1072.yml
Added Eventbrite link for registration
=> Added Eventbrite link for registration

_data/events/SQLSat1071.yml
=> Updated procuresql logo in the image link that did not display.

_data/events/SQLSat1071.yml
Schedule link updated on the website.
=> Schedule link updated.

_data/events/SQLSat1072.yml
Changed registration from Eventbrite to Ticketleap
=> Changed registration from Eventbrite to Ticketleap

_data/events/SQLSat1073.yml
Added sponsor, schedule, precons.
=> SQLSatAustin

_includes/sqlbits-banner.html, assets/css/pass-banner.css
Updates the banner to include the SQL Bits image.
=> Update banner layout for SQL Bits

_includes/sqlbits-banner.html, assets/css/pass-banner.css
=> sql bits banner update

_includes/sqlbits-banner.html
#307 attempting to align the li tag center
=> align banner center

_data/events/SQLSat1071.yml
=> Update sponsor details.

_data/events/SQLSat1076.yml, _posts/2024-07-27-sqlsaturday1076.markdown
=> summit date update Update dates for Summit 2024  #305

_data/events/SQLSat1073.yml
SQLSatAustin - Adjust image size for sponsor logo.
=> SQLSatAustin - Adjust image size

_data/events/SQLSat1076.yml, batonrouge.html
=>  #304 redirect update

_data/events/SQLSat1071.yml
Change of one precon location due to space issues.
=> Change of one precon location due to space issues.

_data/events/SQLSat1076.yml
All the things we were missing before.
=> SQLSATBR: Add basic info

_data/events/SQLSat1073.yml
=> SQLSatAustin - New Sponsor

_data/events/SQLSat1082.yml, _posts/2024-11-02-sqlsaturday1082.markdown
=> ore 2024 test event #363

_data/events/SQLSat1078.yml
=> oc sponsor update

_data/events/SQLSat1080.yml
=> update sponsor link to new tab SQL Saturday South Florida 2024 #344

_data/events/SQLSat1080.yml
=> #344 added CFS

_data/events/SQLSat1083.yml
=> countdown timer

coc/richmond-coc.md
=> coc update SQL Saturday Richmond 2024 #330

_data/events/SQLSat1072.yml
added volunteer link and precon speaker
=> added volunteer link and precon speaker

_data/events/SQLSat1085.yml, _data/otherevents.yml, _posts/2024-08-24-sqlsaturday1085.markdown
=> test event setup #393

_data/events/SQLSat1084.yml, _posts/2024-07-27-sqlsaturday1084.markdown
=> adjust year in title #385

_data/events/SQLSat1086.yml, _posts/2024-10-05-sqlsaturday1086.markdown
=> boston 2024 test event #406

_data/events/SQLSat1088.yml, _posts/2024-06-01-sqlsaturday1088.markdown
=> la test event

_data/events/SQLSat1089.yml, _posts/2024-10-12-sqlsaturday1089.markdown, index.md
=> orlando initial test event #441

_data/events/SQLSat1090.yml, _posts/2024-08-17-sqlsaturday1090.markdown, denver.html
=> denver 2024 initial event from email

_data/events/SQLSat1076.yml
=> Baton Rouge: Add Quest

_data/events/SQLSat1076.yml
=> Baton Rouge: Final Spnsors

_data/events/SQLSat1081.yml
#480 schedule and speaker update
=> schedule and speaker update LA 2024 #428

_data/events/SQLSat1092.yml
=> added cfs link San Diego 2024 #479

_data/events/SQLSat1093.yml
=> updated contacts #503

_data/events/SQLSat1089.yml
=> #441 added CFS and reg links

mn.html
=> redirect update Minnesota 2024 #416

_data/events/SQLSat1086.yml
=> added sios sponsor Boston 2024 #406

_data/events/SQLSat1094.yml, _posts/2024-10-12-sqlsaturday1094.markdown, pittsburgh.html
=> initial test event #516

_data/events/SQLSat1083.yml
=> adjust name and url for site sponsor SQL Sat Albany 2024 #382

_data/events/SQLSat1094.yml
fixed title of venue and sponsorship location #516
=> location updates

_data/events/SQLSat1092.yml
=> cozyroc sponsor San Diego 2024 #479

_data/events/SQLSat1091.yml
=> updaed schedule

_data/events/SQLSat1092.yml
=> added speaker urls San Diego 2024 #479

_data/events/SQLSat1086.yml
#406 adding precon box for tickets
=> fixing precon box

_data/events/SQLSat1094.yml
=> adjust cfs Pittsburgh2024 #516

_data/events/SQLSat1097.yml
=> added reg links SQL Saturday Belo Horizonte 2024 #577

_data/events/SQLSat1082.yml
=> updated sql train info #363

_data/events/SQLSat1093.yml
#503 change requested by email
=> changed prices added CAD

_data/events/SQLSat1092.yml
=> oreilly sponsor San Diego 2024 #479

_data/events/SQLSat1093.yml, _data/otherevents.yml
=> changed description text Toronto 2024 #503

_data/events/SQLSat1086.yml
=> updated schedule Boston 2024 #406

_data/events/SQLSat1092.yml
=> changed precon times San Diego 2024 #479

_data/events/SQLSat1086.yml, _data/otherevents.yml
=> redgate sponsorship Boston 2024 #406

_data/events/SQLSat1082.yml
=> amd sponsorship SQL Sat Oregon and SW Washington 2024 #363

_data/events/SQLSat1093.yml
=> added platinum level Toronto 2024 #503

_data/events/SQLSat1100.yml
=> fix contacts

_data/events/SQLSat1102.yml, _posts/2025-03-08-sqlsaturday1101.markdown, atl.html
=> initial 2025 BI event #703

_data/events/SQLSat1102.yml
Updated the website with correct initial details about the SQL Saturday Atlanta AI & BI.
=> Initial commit for SQL Sat ATL AI & BI site.

_data/events/SQLSat1101.yml
Good day, our CfS is launched - so updating the SQL Saturday with this and other things would be nice.
Thanks!
=> Added CfS for SeaQL 2025

_data/events/SQLSat1097.yml
=> SQL Saturday Belo Horizonte 2024 #577 schedule

_data/events/SQLSat1104.yml, _posts/2025-04-05-sqlsaturday1104.markdown, joinville.html
=> new event #743

_data/otherevents.yml
Revert website from other events list
=> Event Cancellation - CLE Data Rocks 2025

_data/otherevents.yml
=> fix dates #749

haiti.html
=> added redirect

_data/events/SQLSat1107.yml
Minor edit - adding second organizer and tweaking title
=> Add Jeremy as organizer and tweak title

_data/events/SQLSat1102.yml
=> Updated whatsapp group info.

_data/events/SQLSat1102.yml
Updated Mastering AI with Prompt engineering precon details.
=> Updated Mastering AI with Prompt engineering precon details.

_data/events/SQLSat1102.yml
Updated precon info, volunteer signup, and hotel info.
=> Updated precon info, volunteer signup, and hotel info.

_data/events/SQLSat1102.yml
Published schedule url and speaker wall url
=> Published schedule url and speaker wall url

_data/events/SQLSat1102.yml
Updated title for Chris in the PBI for precon.
=> Updated title for Chris in the PBI for precon.

_data/events/SQLSat1111.yml, _posts/2025-05-17-sqlsaturday1111.markdown
=> initial test event from email #826

_data/events/SQLSat1102.yml
Updated the precon speaker for the Power BI precon.
=> Updated the precon speaker

_data/events/SQLSat1112.yml, _posts/2025-05-03-sqlsaturday1112.markdown
=> initial event SQL Sat Austin 2025 #829

_data/events/SQLSat1102.yml
Removed Prompt Engineering precon & updated hotel link to make it clickable.
=> Removed Prompt Engineering precon & updated hotel.

_data/events/SQLSat1111.yml
Update the Raleigh YAML file to include details on a pre-con.
=> Add Raleigh pre-con details

_data/events/SQLSat1113.yml, _posts/2025-06-21-sqlsaturday1113.markdown, sandiego.html
=> SD enw event from email #841

_data/events/SQLSat1102.yml
=> Updated sponsor info.

_data/events/2025/SQLSat1114.yml, _posts/2025-05-23-sqlsaturday1114.markdown
=> new event SQL Sat NYC 2025 #850

_data/events/SQLSat1105.yml
#758 updated from pull request with malformed YML
=> updated precon detail

_data/events/SQLSat1106.yml
=> Richmond - schedule view change

_data/events/2025/SQLSat1114.yml
=> Update SQLSat1114 SQL Sat SLC

_data/events/SQLSat1115.yml, _posts/2025/2025-05-03-sqlsaturday1115.markdown
=> golive #858 cfs and reg

oc.html
=> removed trailing slash SQL Sat Orange County 2025 #858

_data/events/SQLSat1109.yml, _data/events/SQLSat1119.yml, stlouis.html
=> added yt stream SQL Sat Haiti 2025 #771

_data/events/SQLSat1118.yml
=> removed red9 SQL Saturday Truljillo 2025 #997

_data/events/SQLSat1123.yml, _posts/2025-10-18-sqlsaturday1123.markdown
=> initial event as test #1015

_data/events/SQLSat1110.yml
=> Baton Rouge: Add Rubrik

_data/events/SQLSat1124.yml, _posts/2025-09-27-sqlsaturday1124.markdown, mn.html
=> new event #1019

_data/otherevents.yml
Updated the name for Scenic City Summit 
Issue #1030
=> Updated name for "Scenic City Summit"

_data/events/SQLSat1117.yml
=> misc updates SQL Sat St Louis 2025 #985

oregon.html
changing redirect from 2023 to 2024
=> changing redirect from 2023 to 2024

_data/events/SQLSat1117.yml
=> Location update

_data/events/SQLSat1128.yml, _posts/2026-05-02-sqlsaturday1128.markdown, index.md
=> new event #1088

_data/events/SQLSat1117.yml
=> added form link #985

_data/events/SQLSat1125.yml, _posts/2025-09-27-sqlsaturday1125.markdown
=> turn live SQLSatCXS 2025 #1076

_data/events/SQLSat1130.yml, _posts/2025-11-15-sqlsaturday1130.markdown
=> new event SQL Sat Oregon 2025

_data/otherevents.yml
Or would you prefer the link from the Data Saturday site?
https://datasaturdays.com/Event/20260314-datasaturday0076
=> Added Data Saturday #76 - Chicago

_data/events/SQLSat1120.yml, houston.html
=> added precons #991

_data/events/SQLSat1124.yml
=> Updated schedule and register links Minnesota 2025

cxs.html
=> added redirect file SQLSatCXS 2025

pittsburgh.html
=> redirect Pittsburgh 2025

index.md
=> reserved #1154

_data/events/SQLSat1124.yml
added Databricks to sponsors list for SQLSatMN
=> added Databricks to sponsors list for SQLSatMN

_data/events/SQLSat1133.yml, _posts/2025-11-29-sqlsaturday1133.markdown, nz.html
=> new event from #1163

_data/events/SQLSat1130.yml
=> adjust format and college name Oregon and SW Washington 2025

index.md
=> fix same day rebuild issue #1187

_data/events/SQLSat1131.yml
=> adjust plan values per email Toronto 2025
